export const productList =[
    {
        id:1,
        url: 'https://m.media-amazon.com/images/I/61W8CmDd8JS._SX569_.jpg',
        category: 'Universal Visor',
        seller: 'ABS Ltd',
        price:300,
        discription:'RACE COPZ Headlight Windshield Universal Visor for Bajaj Pulsar NS 200 (Black) Universal Visor with NS 200 Visor it Will Run All bike Accessries Model',
        stock:20,
        discount:67
      },
    {   id:2,
        url: 'https://rukminim1.flixcart.com/image/300/300/l51d30w0/shoe/z/w/c/10-mrj1914-10-aadi-white-black-red-original-imagft9k9hydnfjp.jpeg?q=70',
        name: 'TRQ White Shoes',
        category: 'Shoes',
        seller: 'AMZ Seller Ghz',
        price: 1999,
        discription:'TOUCHFAST SK Men Synthetic Leather Casual Sneaker Shoes Elevated Comfort Perfect Casual Shoes for Men SK Men Synthetic Leather Casual Sneaker White Shoes',
        stock:0,
        discount:70
      },
      { id:3,
        url: 'https://m.media-amazon.com/images/I/61iAAHx0YEL._SX569_.jpg',
        name: 'LOREM Watch ',
        category: 'Watches',
        seller: 'Watch Ltd Siyana',
        price: 2599,
        discription:`Fire-Boltt Newly Launched Ninja Call Pro Max 2.01” Display Smart Watch, Bluetooth Calling, 120+ Sports Modes,...`,
        stock:100,
        discount:0

      },
      { id:4,
        url: 'https://m.media-amazon.com/images/I/41nMCgtlA-L._SX300_SY300_QL70_FMwebp_.jpg',
        name: 'AMZ Laptop 8GB RAM',
        category: 'Laptops',
        seller: 'Delhi Laptops',
        price: 50000,
        discription:`Dell Inspiron 7420 2in1 Touch Laptop,12th Gen Intel Core i3-1215U, 8GB/256GB SSD/14.0" (35.56Cms) FHD+ WVA 250 nits/Backlit KB + FPR Month McAfee/Platinum Silver/1.57KG`,
        stock:190,
        discount:67
      },
      { id:5,
        url: 'https://m.media-amazon.com/images/I/51pa0mHkv+L._SX569_.jpg',
        name: 'Security Camera',
        category: 'CCTV',
        seller: 'Camron LTD',
        price: 4000,
        discription:`SINLOE 2 MP Color Night Vision Wired Day/Night 24 Hour Full Color Vision 1080p Full HD  CCTV Surveillance Camera Compatible for 2MP and Above DVR- White`,
        stock:20,
        discount:78
      },
      { id:6,
        url: 'https://m.media-amazon.com/images/I/41SrxS4-vrL._UX569_.jpg',
        name: 'Watch',
        category: 'Watches',
        seller: 'Watch Ltd',
        price: 2000,
        discription:"Acnos® Premium Brand Arrow Blk Arrow Boys Mens Black Wrist Watch for Boys Analog Watch for Men Pack of 1",
        stock:67,
        discount:10
        
      },
      { id:7,
        url: 'https://m.media-amazon.com/images/I/41J1kYfM6PL.jpg',
        name: 'C',
        category: 'Camera',
        seller: 'SLR EOS',
        price: 100,
        discription:"Canon EOS 200D II 24.1MP Digital SLR Camera + EF-S 18-55mm f4 is STM Lens (Black) EOS 200D II 24.1MP Digital SLR ",
        stock:0,
        discount:50
      },
      
    {
        id:8,
        url: 'https://m.media-amazon.com/images/I/61+iqGRxv3L._SX679_.jpg',
        category: 'Helmet',
        seller: 'IGN_4 Ltd',
        price:5500,
        discription:'Ignyte IGN-4 Trever ISI / DOT Certified Double Visor Full Face Helmet Outer Anti-Fog Clear Visor and Inner Smoke Sun Shield',
        stock:0,
        discount:10
     },
      {
        id:9,
        url: 'https://m.media-amazon.com/images/I/71T5NVOgbpL._SX679_.jpg',
        category: 'Apple',
        seller: 'USA CO',
        price:105500,
        discription:'Apple iPhone 14 Pro Max (128 GB) - Gold',
        stock:90,
        discount:66
      },
      {
        id:10,
        url: 'https://m.media-amazon.com/images/I/7131mkC0ZnL._SX679_.jpg',
        category: 'Smart Watch',
        seller: 'ICOR LCD',
        price:1500,
        discription:'Hammer Ace Ultra 1.96" Bluetooth Calling Smart Watch with Rotating Crown, Metallic Body, 600 Nits AOD, Spo2, HR, BP & 2 Straps (Grey & Orange)',
        stock:880,
        discount:90
      },
      {
        id:11,
        url: 'https://m.media-amazon.com/images/I/61kWB+uzR2L._SX569_.jpg',
        category: 'Headphone',
        seller: 'boat LMT',
        price:500,
        discription:'boAt Rockerz 370 On Ear Bluetooth Headphones with Upto 12 Hours Playtime, Cozy Padded Earcups and Bluetooth v5.0, with Mic (Buoyant Black)',
        stock:0,
        discount:50
      },
      {
        id:12,
        url: 'https://m.media-amazon.com/images/I/613SAOPmLeL._SX679_.jpg',
        category: 'One Plus',
        seller: 'ROMAN LIT',
        price:65500,
        discription:'OnePlus 11R 5G (Galactic Silver, 8GB RAM, 128GB Storage)',
        stock:98,
        discount:100
      },
      {
        id:13,
        url: 'https://m.media-amazon.com/images/I/414myTtnlmL._SX300_SY300_QL70_FMwebp_.jpg',
        category: 'Earbuds',
        seller: 'PTron Bassbuds',
        price:650,
        discription:'PTron Bassbuds Air in-Ear TWS Earbuds with 13mm Driver for Immersive Sound, 32Hrs Playtime, Clear Calls, Bluetooth V5.1, Touch Control, TypeC Fast Charging, Voice Assist & IPX4 Water Resistant (Blue)',
        stock:0,
        discount:88
      },
      {
        id:14,
        url: 'https://m.media-amazon.com/images/I/61xzutxSl8L._SX569_.jpg',
        category: 'Acer',
        seller: 'INTEL core',
        price:89000,
        discription:'Acer Aspire 5 Gaming Laptop Intel Core i5 12th gen (16 GB/512 GB SSD/Win11 Home/4GB Graphics/RTX 2050) A515-57G (15.6" FHD Display, 1.8 Kg) - Flat 10% cashback on Amazon Pay ICICI Credit Card',
        stock:0,
        discount:50
      },
      {
        id:15,
        url: 'https://m.media-amazon.com/images/I/611rQWZa5rL._SX679_.jpg',
        category: 'iQOO Neo',
        seller: 'Gen Plus',
        price:47000,
        discription:'iQOO Neo 7 Pro 5G (Dark Storm, 8GB RAM, 128GB Storage) | Snapdragon® 8+ Gen 1 | Independent Gaming Chip | Flagship 50MP OIS Camera | AG Glass Design',
        stock:99,
        discount:90
      },
      {
        id:16,
        url: 'https://m.media-amazon.com/images/I/916acEhBkcL._SX679_.jpg',
        category: 'Apple Watch',
        seller: 'USA Coo',
        price:150000,
        discription:'Apple Watch Ultra [GPS + Cellular 49 mm] Smart Watch w/Rugged Titanium Case & Green Alpine Loop - Small. Fitness Tracker, Precision GPS, Action Button, Extra-Long BatteryLife, Brighter Retina Display',
        stock:0,
        discount:50
      },
    ]